// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_create_tree_constructor1
SEXP test_create_tree_constructor1(const Rcpp::DataFrame& df, SEXP depth, SEXP upper_bound, SEXP name);
RcppExport SEXP _treehunt_test_create_tree_constructor1(SEXP dfSEXP, SEXP depthSEXP, SEXP upper_boundSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< SEXP >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< SEXP >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_tree_constructor1(df, depth, upper_bound, name));
    return rcpp_result_gen;
END_RCPP
}
// test_create_tree_constructor2
SEXP test_create_tree_constructor2(const Rcpp::IntegerVector& vect);
RcppExport SEXP _treehunt_test_create_tree_constructor2(SEXP vectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type vect(vectSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_tree_constructor2(vect));
    return rcpp_result_gen;
END_RCPP
}
// test_tree_info
Rcpp::List test_tree_info(SEXP ptr);
RcppExport SEXP _treehunt_test_tree_info(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_tree_info(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treehunt_test_create_tree_constructor1", (DL_FUNC) &_treehunt_test_create_tree_constructor1, 4},
    {"_treehunt_test_create_tree_constructor2", (DL_FUNC) &_treehunt_test_create_tree_constructor2, 1},
    {"_treehunt_test_tree_info", (DL_FUNC) &_treehunt_test_tree_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_treehunt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
