// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_create_patient_data_int
SEXP test_create_patient_data_int(Rcpp::DataFrame df, SEXP node_column, SEXP target_column, SEXP tree_ptr);
RcppExport SEXP _treehunt_test_create_patient_data_int(SEXP dfSEXP, SEXP node_columnSEXP, SEXP target_columnSEXP, SEXP tree_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< SEXP >::type node_column(node_columnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target_column(target_columnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_patient_data_int(df, node_column, target_column, tree_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_create_patient_data_double
SEXP test_create_patient_data_double(Rcpp::DataFrame df, SEXP node_column, SEXP target_column, SEXP tree_ptr);
RcppExport SEXP _treehunt_test_create_patient_data_double(SEXP dfSEXP, SEXP node_columnSEXP, SEXP target_columnSEXP, SEXP tree_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< SEXP >::type node_column(node_columnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target_column(target_columnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_patient_data_double(df, node_column, target_column, tree_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_patient_data_size
int test_patient_data_size(SEXP data_ptr);
RcppExport SEXP _treehunt_test_patient_data_size(SEXP data_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr(data_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_patient_data_size(data_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_patient_data_get_nodes
Rcpp::IntegerVector test_patient_data_get_nodes(SEXP data_ptr, int patient_idx);
RcppExport SEXP _treehunt_test_patient_data_get_nodes(SEXP data_ptrSEXP, SEXP patient_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr(data_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type patient_idx(patient_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(test_patient_data_get_nodes(data_ptr, patient_idx));
    return rcpp_result_gen;
END_RCPP
}
// test_patient_data_get_target
int test_patient_data_get_target(SEXP data_ptr, int patient_idx);
RcppExport SEXP _treehunt_test_patient_data_get_target(SEXP data_ptrSEXP, SEXP patient_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr(data_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type patient_idx(patient_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(test_patient_data_get_target(data_ptr, patient_idx));
    return rcpp_result_gen;
END_RCPP
}
// test_patient_data_get_target_double
double test_patient_data_get_target_double(SEXP data_ptr, int patient_idx);
RcppExport SEXP _treehunt_test_patient_data_get_target_double(SEXP data_ptrSEXP, SEXP patient_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr(data_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type patient_idx(patient_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(test_patient_data_get_target_double(data_ptr, patient_idx));
    return rcpp_result_gen;
END_RCPP
}
// test_patient_data_has_combination
bool test_patient_data_has_combination(SEXP data_ptr, int patient_idx, Rcpp::IntegerVector combination);
RcppExport SEXP _treehunt_test_patient_data_has_combination(SEXP data_ptrSEXP, SEXP patient_idxSEXP, SEXP combinationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr(data_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type patient_idx(patient_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type combination(combinationSEXP);
    rcpp_result_gen = Rcpp::wrap(test_patient_data_has_combination(data_ptr, patient_idx, combination));
    return rcpp_result_gen;
END_RCPP
}
// test_create_solution
SEXP test_create_solution(Rcpp::IntegerVector nodes);
RcppExport SEXP _treehunt_test_create_solution(SEXP nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type nodes(nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_solution(nodes));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_get_nodes
Rcpp::IntegerVector test_solution_get_nodes(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_get_nodes(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_get_nodes(sol_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_size
int test_solution_size(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_size(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_size(sol_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_empty
bool test_solution_empty(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_empty(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_empty(sol_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_set_score
void test_solution_set_score(SEXP sol_ptr, double score);
RcppExport SEXP _treehunt_test_solution_set_score(SEXP sol_ptrSEXP, SEXP scoreSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type score(scoreSEXP);
    test_solution_set_score(sol_ptr, score);
    return R_NilValue;
END_RCPP
}
// test_solution_get_score
double test_solution_get_score(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_get_score(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_get_score(sol_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_is_score_computed
bool test_solution_is_score_computed(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_is_score_computed(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_is_score_computed(sol_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_invalidate_score
void test_solution_invalidate_score(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_invalidate_score(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    test_solution_invalidate_score(sol_ptr);
    return R_NilValue;
END_RCPP
}
// test_solution_get_hash
double test_solution_get_hash(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_get_hash(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_get_hash(sol_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_invalidate_hash
void test_solution_invalidate_hash(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_invalidate_hash(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    test_solution_invalidate_hash(sol_ptr);
    return R_NilValue;
END_RCPP
}
// test_solution_invalidate
void test_solution_invalidate(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_invalidate(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    test_solution_invalidate(sol_ptr);
    return R_NilValue;
END_RCPP
}
// test_solution_is_valid
bool test_solution_is_valid(SEXP sol_ptr, SEXP tree_ptr);
RcppExport SEXP _treehunt_test_solution_is_valid(SEXP sol_ptrSEXP, SEXP tree_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_is_valid(sol_ptr, tree_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_contains
bool test_solution_contains(SEXP sol_ptr, int node);
RcppExport SEXP _treehunt_test_solution_contains(SEXP sol_ptrSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_contains(sol_ptr, node));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_print
void test_solution_print(SEXP sol_ptr);
RcppExport SEXP _treehunt_test_solution_print(SEXP sol_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    test_solution_print(sol_ptr);
    return R_NilValue;
END_RCPP
}
// test_solution_less_than
bool test_solution_less_than(SEXP sol1_ptr, SEXP sol2_ptr);
RcppExport SEXP _treehunt_test_solution_less_than(SEXP sol1_ptrSEXP, SEXP sol2_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol1_ptr(sol1_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sol2_ptr(sol2_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_less_than(sol1_ptr, sol2_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_greater_than
bool test_solution_greater_than(SEXP sol1_ptr, SEXP sol2_ptr);
RcppExport SEXP _treehunt_test_solution_greater_than(SEXP sol1_ptrSEXP, SEXP sol2_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol1_ptr(sol1_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sol2_ptr(sol2_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_greater_than(sol1_ptr, sol2_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_equals
bool test_solution_equals(SEXP sol1_ptr, SEXP sol2_ptr);
RcppExport SEXP _treehunt_test_solution_equals(SEXP sol1_ptrSEXP, SEXP sol2_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol1_ptr(sol1_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sol2_ptr(sol2_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_equals(sol1_ptr, sol2_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_create_random_valid_solution
SEXP test_create_random_valid_solution(SEXP tree_ptr, int target_size, int seed, bool exact_size);
RcppExport SEXP _treehunt_test_create_random_valid_solution(SEXP tree_ptrSEXP, SEXP target_sizeSEXP, SEXP seedSEXP, SEXP exact_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type target_size(target_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_size(exact_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_random_valid_solution(tree_ptr, target_size, seed, exact_size));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_mutate_swap_type2
SEXP test_solution_mutate_swap_type2(SEXP sol_ptr, SEXP tree_ptr, int seed);
RcppExport SEXP _treehunt_test_solution_mutate_swap_type2(SEXP sol_ptrSEXP, SEXP tree_ptrSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_mutate_swap_type2(sol_ptr, tree_ptr, seed));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_mutate_add_remove_type1
SEXP test_solution_mutate_add_remove_type1(SEXP sol_ptr, SEXP tree_ptr, double alpha, int seed);
RcppExport SEXP _treehunt_test_solution_mutate_add_remove_type1(SEXP sol_ptrSEXP, SEXP tree_ptrSEXP, SEXP alphaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_mutate_add_remove_type1(sol_ptr, tree_ptr, alpha, seed));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_mutate_replace_type1
SEXP test_solution_mutate_replace_type1(SEXP sol_ptr, SEXP tree_ptr, int seed);
RcppExport SEXP _treehunt_test_solution_mutate_replace_type1(SEXP sol_ptrSEXP, SEXP tree_ptrSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol_ptr(sol_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_mutate_replace_type1(sol_ptr, tree_ptr, seed));
    return rcpp_result_gen;
END_RCPP
}
// test_solution_crossover_single_point
Rcpp::List test_solution_crossover_single_point(SEXP sol1_ptr, SEXP sol2_ptr, SEXP tree_ptr, int seed);
RcppExport SEXP _treehunt_test_solution_crossover_single_point(SEXP sol1_ptrSEXP, SEXP sol2_ptrSEXP, SEXP tree_ptrSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sol1_ptr(sol1_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sol2_ptr(sol2_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(test_solution_crossover_single_point(sol1_ptr, sol2_ptr, tree_ptr, seed));
    return rcpp_result_gen;
END_RCPP
}
// test_create_tree_constructor1
SEXP test_create_tree_constructor1(const Rcpp::DataFrame& df, SEXP depth, SEXP upper_bound, SEXP name);
RcppExport SEXP _treehunt_test_create_tree_constructor1(SEXP dfSEXP, SEXP depthSEXP, SEXP upper_boundSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< SEXP >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< SEXP >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_tree_constructor1(df, depth, upper_bound, name));
    return rcpp_result_gen;
END_RCPP
}
// test_create_tree_constructor2
SEXP test_create_tree_constructor2(const Rcpp::IntegerVector& vect);
RcppExport SEXP _treehunt_test_create_tree_constructor2(SEXP vectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type vect(vectSEXP);
    rcpp_result_gen = Rcpp::wrap(test_create_tree_constructor2(vect));
    return rcpp_result_gen;
END_RCPP
}
// test_tree_info
Rcpp::List test_tree_info(SEXP ptr);
RcppExport SEXP _treehunt_test_tree_info(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_tree_info(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treehunt_test_create_patient_data_int", (DL_FUNC) &_treehunt_test_create_patient_data_int, 4},
    {"_treehunt_test_create_patient_data_double", (DL_FUNC) &_treehunt_test_create_patient_data_double, 4},
    {"_treehunt_test_patient_data_size", (DL_FUNC) &_treehunt_test_patient_data_size, 1},
    {"_treehunt_test_patient_data_get_nodes", (DL_FUNC) &_treehunt_test_patient_data_get_nodes, 2},
    {"_treehunt_test_patient_data_get_target", (DL_FUNC) &_treehunt_test_patient_data_get_target, 2},
    {"_treehunt_test_patient_data_get_target_double", (DL_FUNC) &_treehunt_test_patient_data_get_target_double, 2},
    {"_treehunt_test_patient_data_has_combination", (DL_FUNC) &_treehunt_test_patient_data_has_combination, 3},
    {"_treehunt_test_create_solution", (DL_FUNC) &_treehunt_test_create_solution, 1},
    {"_treehunt_test_solution_get_nodes", (DL_FUNC) &_treehunt_test_solution_get_nodes, 1},
    {"_treehunt_test_solution_size", (DL_FUNC) &_treehunt_test_solution_size, 1},
    {"_treehunt_test_solution_empty", (DL_FUNC) &_treehunt_test_solution_empty, 1},
    {"_treehunt_test_solution_set_score", (DL_FUNC) &_treehunt_test_solution_set_score, 2},
    {"_treehunt_test_solution_get_score", (DL_FUNC) &_treehunt_test_solution_get_score, 1},
    {"_treehunt_test_solution_is_score_computed", (DL_FUNC) &_treehunt_test_solution_is_score_computed, 1},
    {"_treehunt_test_solution_invalidate_score", (DL_FUNC) &_treehunt_test_solution_invalidate_score, 1},
    {"_treehunt_test_solution_get_hash", (DL_FUNC) &_treehunt_test_solution_get_hash, 1},
    {"_treehunt_test_solution_invalidate_hash", (DL_FUNC) &_treehunt_test_solution_invalidate_hash, 1},
    {"_treehunt_test_solution_invalidate", (DL_FUNC) &_treehunt_test_solution_invalidate, 1},
    {"_treehunt_test_solution_is_valid", (DL_FUNC) &_treehunt_test_solution_is_valid, 2},
    {"_treehunt_test_solution_contains", (DL_FUNC) &_treehunt_test_solution_contains, 2},
    {"_treehunt_test_solution_print", (DL_FUNC) &_treehunt_test_solution_print, 1},
    {"_treehunt_test_solution_less_than", (DL_FUNC) &_treehunt_test_solution_less_than, 2},
    {"_treehunt_test_solution_greater_than", (DL_FUNC) &_treehunt_test_solution_greater_than, 2},
    {"_treehunt_test_solution_equals", (DL_FUNC) &_treehunt_test_solution_equals, 2},
    {"_treehunt_test_create_random_valid_solution", (DL_FUNC) &_treehunt_test_create_random_valid_solution, 4},
    {"_treehunt_test_solution_mutate_swap_type2", (DL_FUNC) &_treehunt_test_solution_mutate_swap_type2, 3},
    {"_treehunt_test_solution_mutate_add_remove_type1", (DL_FUNC) &_treehunt_test_solution_mutate_add_remove_type1, 4},
    {"_treehunt_test_solution_mutate_replace_type1", (DL_FUNC) &_treehunt_test_solution_mutate_replace_type1, 3},
    {"_treehunt_test_solution_crossover_single_point", (DL_FUNC) &_treehunt_test_solution_crossover_single_point, 4},
    {"_treehunt_test_create_tree_constructor1", (DL_FUNC) &_treehunt_test_create_tree_constructor1, 4},
    {"_treehunt_test_create_tree_constructor2", (DL_FUNC) &_treehunt_test_create_tree_constructor2, 1},
    {"_treehunt_test_tree_info", (DL_FUNC) &_treehunt_test_tree_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_treehunt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
