# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
.test_create_patient_data_int <- function(df, node_column, target_column, tree_ptr) {
    .Call(`_treehunt_test_create_patient_data_int`, df, node_column, target_column, tree_ptr)
}

#' @keywords internal
.test_create_patient_data_double <- function(df, node_column, target_column, tree_ptr) {
    .Call(`_treehunt_test_create_patient_data_double`, df, node_column, target_column, tree_ptr)
}

#' @keywords internal
.test_patient_data_size <- function(data_ptr) {
    .Call(`_treehunt_test_patient_data_size`, data_ptr)
}

#' @keywords internal
.test_patient_data_get_nodes <- function(data_ptr, patient_idx) {
    .Call(`_treehunt_test_patient_data_get_nodes`, data_ptr, patient_idx)
}

#' @keywords internal
.test_patient_data_get_target <- function(data_ptr, patient_idx) {
    .Call(`_treehunt_test_patient_data_get_target`, data_ptr, patient_idx)
}

#' @keywords internal
.test_patient_data_get_target_double <- function(data_ptr, patient_idx) {
    .Call(`_treehunt_test_patient_data_get_target_double`, data_ptr, patient_idx)
}

#' @keywords internal
.test_patient_data_has_combination <- function(data_ptr, patient_idx, combination) {
    .Call(`_treehunt_test_patient_data_has_combination`, data_ptr, patient_idx, combination)
}

#' Internal C++ engine for the PWP Rao genetic algorithm
#'
#' Use \code{run_pwp_genetic_algorithm()} from R.
#' @keywords internal
run_genetic_algorithm_pwp_cpp <- function(patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column, score_context, seed_population = NULL, population_size = 100L, epochs = 1000L, mutation_rate = 0.1, prob_mutation_type1 = 0.2, crossover_rate = 0.8, elite_count = 2L, tournament_size = 3L, alpha = 1.0, diversity = FALSE, seed = 1L, verbose = FALSE) {
    .Call(`_treehunt_run_genetic_algorithm_pwp_cpp`, patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column, score_context, seed_population, population_size, epochs, mutation_rate, prob_mutation_type1, crossover_rate, elite_count, tournament_size, alpha, diversity, seed, verbose)
}

#' Internal C++ engine for PWP Rao MCMC
#'
#' Use \code{run_pwp_mcmc()} from R.
#' @keywords internal
run_mcmc_pwp_cpp <- function(patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column, score_context, epochs = 100000, temperature = 1.0, n_results = 20, cocktail_size = 2, prob_type1 = 0.01, beta = 20, max_score = 50.0, seed = 1L, verbose = FALSE, burn_in = 0, store_trace = FALSE) {
    .Call(`_treehunt_run_mcmc_pwp_cpp`, patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column, score_context, epochs, temperature, n_results, cocktail_size, prob_type1, beta, max_score, seed, verbose, burn_in, store_trace)
}

#' Evaluate PWP Rao statistics for specified combinations
#'
#' @keywords internal
score_pwp_combinations_cpp <- function(combinations, index_base, patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column, score_context) {
    .Call(`_treehunt_score_pwp_combinations_cpp`, combinations, index_base, patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column, score_context)
}

#' Construct one hierarchical combination indicator
#'
#' @keywords internal
pwp_combination_flag_cpp <- function(combination, index_base, patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column) {
    .Call(`_treehunt_pwp_combination_flag_cpp`, combination, index_base, patient_data, node_column, target_column, id_column, tree, depth_column, upper_bound_column, name_column)
}

#' @keywords internal
.test_create_solution <- function(nodes) {
    .Call(`_treehunt_test_create_solution`, nodes)
}

#' @keywords internal
.test_solution_get_nodes <- function(sol_ptr) {
    .Call(`_treehunt_test_solution_get_nodes`, sol_ptr)
}

#' @keywords internal
.test_solution_size <- function(sol_ptr) {
    .Call(`_treehunt_test_solution_size`, sol_ptr)
}

#' @keywords internal
.test_solution_empty <- function(sol_ptr) {
    .Call(`_treehunt_test_solution_empty`, sol_ptr)
}

#' @keywords internal
.test_solution_set_score <- function(sol_ptr, score) {
    invisible(.Call(`_treehunt_test_solution_set_score`, sol_ptr, score))
}

#' @keywords internal
.test_solution_get_score <- function(sol_ptr) {
    .Call(`_treehunt_test_solution_get_score`, sol_ptr)
}

#' @keywords internal
.test_solution_is_score_computed <- function(sol_ptr) {
    .Call(`_treehunt_test_solution_is_score_computed`, sol_ptr)
}

#' @keywords internal
.test_solution_invalidate_score <- function(sol_ptr) {
    invisible(.Call(`_treehunt_test_solution_invalidate_score`, sol_ptr))
}

#' @keywords internal
.test_solution_get_hash <- function(sol_ptr) {
    .Call(`_treehunt_test_solution_get_hash`, sol_ptr)
}

#' @keywords internal
.test_solution_invalidate_hash <- function(sol_ptr) {
    invisible(.Call(`_treehunt_test_solution_invalidate_hash`, sol_ptr))
}

#' @keywords internal
.test_solution_invalidate <- function(sol_ptr) {
    invisible(.Call(`_treehunt_test_solution_invalidate`, sol_ptr))
}

#' @keywords internal
.test_solution_is_valid <- function(sol_ptr, tree_ptr) {
    .Call(`_treehunt_test_solution_is_valid`, sol_ptr, tree_ptr)
}

#' @keywords internal
.test_solution_contains <- function(sol_ptr, node) {
    .Call(`_treehunt_test_solution_contains`, sol_ptr, node)
}

#' @keywords internal
.test_solution_print <- function(sol_ptr) {
    invisible(.Call(`_treehunt_test_solution_print`, sol_ptr))
}

#' @keywords internal
.test_solution_less_than <- function(sol1_ptr, sol2_ptr) {
    .Call(`_treehunt_test_solution_less_than`, sol1_ptr, sol2_ptr)
}

#' @keywords internal
.test_solution_greater_than <- function(sol1_ptr, sol2_ptr) {
    .Call(`_treehunt_test_solution_greater_than`, sol1_ptr, sol2_ptr)
}

#' @keywords internal
.test_solution_equals <- function(sol1_ptr, sol2_ptr) {
    .Call(`_treehunt_test_solution_equals`, sol1_ptr, sol2_ptr)
}

#' @keywords internal
.test_create_random_valid_solution <- function(tree_ptr, target_size, seed, exact_size = TRUE) {
    .Call(`_treehunt_test_create_random_valid_solution`, tree_ptr, target_size, seed, exact_size)
}

#' @keywords internal
.test_solution_mutate_swap_type2 <- function(sol_ptr, tree_ptr, seed) {
    .Call(`_treehunt_test_solution_mutate_swap_type2`, sol_ptr, tree_ptr, seed)
}

#' @keywords internal
.test_solution_mutate_add_remove_type1 <- function(sol_ptr, tree_ptr, alpha, seed) {
    .Call(`_treehunt_test_solution_mutate_add_remove_type1`, sol_ptr, tree_ptr, alpha, seed)
}

#' @keywords internal
.test_solution_mutate_genetic_algorithm <- function(sol_ptr, tree_ptr, alpha, prob_mutation_type1, seed) {
    .Call(`_treehunt_test_solution_mutate_genetic_algorithm`, sol_ptr, tree_ptr, alpha, prob_mutation_type1, seed)
}

#' @keywords internal
.test_solution_mutate_replace_type1 <- function(sol_ptr, tree_ptr, seed) {
    .Call(`_treehunt_test_solution_mutate_replace_type1`, sol_ptr, tree_ptr, seed)
}

#' @keywords internal
.test_solution_crossover_single_point <- function(sol1_ptr, sol2_ptr, tree_ptr, seed) {
    .Call(`_treehunt_test_solution_crossover_single_point`, sol1_ptr, sol2_ptr, tree_ptr, seed)
}

#' @keywords internal
.test_create_tree_constructor1 <- function(df, depth, upper_bound = NULL, name = NULL) {
    .Call(`_treehunt_test_create_tree_constructor1`, df, depth, upper_bound, name)
}

#' @keywords internal
.test_create_tree_constructor2 <- function(vect) {
    .Call(`_treehunt_test_create_tree_constructor2`, vect)
}

#' @keywords internal
.test_tree_info <- function(ptr) {
    .Call(`_treehunt_test_tree_info`, ptr)
}

#' Run MCMC Algorithm for Estimation of Score Distribution Among Nodes of The
#' Tree
#'
#' Performs a Modified Metropolis-Hastings MCMC sampling to estimate the score
#' distribution of nodes combination of a given \emph{cocktail_size}. The
#' algorithm explores the space of tree combinations using a proposal law 
#' composed of two mutation types.
#'
#' @param patient_data A data.frame containing patient information with at least
#'   a node column and a target column.
#' @param node_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the column containing drug codes. This column should be either:
#'   \itemize{
#'     \item A list of integer vectors: \code{list(c(1,2), c(3), c(4,5))}
#'     \item A character vector with comma-separated values: \code{c("1,2", "3", "4,5")}
#'   }
#' @param id_column Optional observation-unit identifier column, given by name
#'   or one-based position. Required for Wilcoxon and residual patient-level scores.
#' @param target_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the target/outcome column. Integer values are treated as binary for now,
#'   numeric values with non-0/1 entries are treated as continuous.
#' @param tree_depth An integer vector specifying the depth of each node in the
#'   tree structure. Must start at depth 1 and children must be at depth+1 of
#'   their parent.
#' @param epochs Number of MCMC iterations to run.
#' @param temperature Temperature parameter for the Metropolis-Hastings acceptance
#'   probability. Higher values lead to an easiest acceptance of lower score. Default: 1.0.
#' @param n_results Number of top solutions to track and return. Default: 10.
#' @param cocktail_size Target size of drug combinations to search for. Default: 2.
#' @param prob_type1 Probability of using Type 1 mutation (random generation) vs
#'   Type 2 mutation (local swap). Default: 0.01.
#' @param beta Strict support threshold: filtered results require more than
#'   beta covered observations (or distinct patients for patient-level scores). Default: 4.
#' @param max_score Finite positive cap applied to scores before Metropolis-Hastings
#'   acceptance, importance weighting and binning. Default: 200.0.
#' @param score_type Scoring function to use. Either "hypergeometric" for the
#'   hypergeometric test, "relative_risk" for relative risk calculation, or "wilcoxon"
#'   for the wilcoxon test with continuous output.
#'   Default: "hypergeometric".
#' @param verbose If TRUE, prints progress and statistics during the run.
#'   Default: FALSE.
#' @param seed Optional non-negative integer seed for the C++ random-number
#'   generator. If \code{NULL}, the generator is initialized non-deterministically.
#'
#' @param burn_in Number of initial iterations excluded from all distributions,
#'   top solutions and the optional trace. Must be smaller than epochs. Default: 0.
#' @param store_trace If TRUE, return the retained capped score, support and
#'   zero-based node vector for each iteration. Default FALSE avoids this storage.
#'
#' @return A list containing:
#'   \describe{
#'     \item{top_solutions}{List of zero-based node vectors for the top scoring solutions}
#'     \item{top_scores}{Numeric vector of scores for the top solutions}
#'     \item{top_solutions_filtered}{Top solutions meeting the beta threshold}
#'     \item{top_scores_filtered}{Scores for the filtered solutions}
#'     \item{score_distribution}{Histogram of retained capped scores (0.1-wide bins and a cap bin)}
#'     \item{score_distribution_filtered}{Histogram for solutions meeting beta threshold}
#'     \item{outstanding_scores}{Retained capped scores equal to max_score}
#'     \item{uniform_reference}{Uniform-reference distribution and weight ESS}
#'     \item{uniform_reference_filtered}{Support-filtered uniform reference and ESS}
#'     \item{reference_parameters}{Temperature, score cap, support and burn-in settings}
#'     \item{trace}{Retained trajectory, only when store_trace is TRUE}
#'     \item{statistics}{List of run statistics including acceptance rates}
#'   }
#'
#' @details
#' The stationary target on observed subsets of \code{cocktail_size} distinct
#' nodes is proportional to \eqn{\exp(S(C)/T)}, where \eqn{S} is capped at
#' \code{max_score}. Ancestor-descendant pairs are included in this MCMC space;
#' genetic-algorithm validity filtering is a separate operation.
#'
#' Type 1 proposes a uniform subset of distinct nodes. Type 2 replaces a node
#' by a parent or child not already in the combination. Its Hastings correction
#' is \eqn{|V(C)|/|V(C')|}, counting these possible local moves before rejecting
#' proposals absent from the data. Each acceptance probability is the minimum
#' of 1 and \eqn{\exp((S(C')-S(C))/T)} times the applicable proposal correction.
#' A positive \code{prob_type1} connects the observed state space.
#'
#' At every retained iteration, including rejected moves, weights proportional
#' to \eqn{\exp(-S(C)/T)} recover the uniform combination reference. Weights are
#' computed from exact capped scores before grouping into bins. They are
#' rescaled internally to avoid numerical underflow. The filtered reference
#' conditions on support strictly greater than \code{beta}, with its own ESS.
#' This estimates a uniform law on combinations, not on distinct score values.
#'
#' \code{uniform_reference} and \code{uniform_reference_filtered} each contain
#' \code{distribution}, \code{n_samples}, and \code{weight_ess}. The distribution
#' columns are \code{lower}, \code{upper}, \code{probability}, \code{cdf} and
#' \code{upper_tail}. Bins are [lower, upper), except the final singleton bin
#' at the cap. CDF includes the current bin; upper_tail includes it and all
#' subsequent bins. Empty references have NA probabilities and ESS.
#' ESS is \eqn{(\sum w)^2/\sum w^2}; it measures weight concentration and does
#' not account for MCMC autocorrelation. Check mixing separately and choose
#' an appropriate \code{burn_in}. See \code{\link{uniform_score_reference}}
#' for post-processing an optionally stored trace without binning.
#'
#' @examples
#' dat <- data.frame(outcome = c(1L, 1L, 0L, 0L))
#' dat$nodes <- list(c(0L, 1L), 0L, 1L, 1L)
#' tree <- data.frame(Depth = c(1L, 1L))
#' result <- run_mcmc(dat, "nodes", "outcome", c(1L, 1L),
#'   epochs = 100, cocktail_size = 1, seed = 42)
#' result$uniform_reference$weight_ess
#'
#' @export
run_mcmc <- function(patient_data, node_column, target_column, tree_depth, epochs, temperature = 1.0, n_results = 10, cocktail_size = 2, prob_type1 = 0.01, beta = 4, max_score = 200.0, score_type = "hypergeometric", verbose = FALSE, seed = NULL, burn_in = 0, store_trace = FALSE, id_column = NULL) {
    .Call(`_treehunt_run_mcmc`, patient_data, node_column, target_column, tree_depth, epochs, temperature, n_results, cocktail_size, prob_type1, beta, max_score, score_type, verbose, seed, burn_in, store_trace, id_column)
}

#' Run Genetic Algorithm for High Score Nodes Combination Search
#'
#' Performs a genetic algorithm search to find optimal node combinations that
#' maximize a specified score function. The algorithm evolves a population of
#' solutions through selection, crossover, and mutation operations.
#'
#' @param patient_data A data.frame containing patient information with at least
#'   a node column and a target column.
#' @param node_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the column containing node indexes. This column should be either:
#'   \itemize{
#'     \item A list of integer vectors: \code{list(c(1,2), c(3), c(4,5))} (0 indexed Note : Might be wise to change this)
#'     \item A character vector with comma-separated values: \code{c("1,2", "3", "4,5")}
#'   }
#' @param target_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the target/outcome column. Integer values are treated as binary,
#'   numeric values with non-0/1 entries are treated as continuous.
#' @param tree_depth An integer vector specifying the depth of each node in the
#'   tree structure. Must start at depth 1 and children must be at depth+1 of
#'   their parent.
#' @param seed_population A \code{list} of integer vectors representing an initial 
#'   population (vector of 1-based tree index). If provided, these individuals 
#'   will be included in the first generation . If the list contains fewer 
#'   individuals than \code{population_size}, the remainder will be initialized 
#'   randomly. If \code{NULL} (the default), the entire initial population 
#'   is generated randomly.
#' @param population_size Number of solutions in the population. Default: 100.
#' @param epochs Number of generations to evolve. Default: 1000.
#' @param mutation_rate Probability of mutating each offspring. Default: 0.1.
#' @param prob_mutation_type1 When mutation occurs, probability of using Type 1
#'   (add/remove) vs Type 2 (swap) mutation. Default: 0.2.
#' @param crossover_rate Probability of applying crossover to selected parents.
#'   Default: 0.8.
#' @param elite_count Number of top solutions to preserve unchanged each generation.
#'   Default: 0.
#' @param tournament_size Number of solutions competing in tournament selection.
#'   Default: 2.
#' @param alpha Parameter controlling the add/remove mutation bias. Higher values
#'   favor adding nodes. Default: 1.0.
#' @param score_type Scoring function to use. Either "hypergeometric" for the
#'   hypergeometric test, "relative_risk" for relative risk calculation, or "wilcoxon"
#'   for the wilcoxon test with continuous output.
#' @param diversity If TRUE, applies a diversity penalty to encourage exploration
#'   of different solutions. Default: FALSE.
#' @param verbose If TRUE, prints progress during the run. Default: FALSE.
#' @param seed Optional non-negative integer seed for the C++ random-number
#'   generator. If \code{NULL}, the generator is initialized non-deterministically.
#'
#' @return A list containing:
#'   \describe{
#'     \item{final_population}{The complete final population of solutions}
#'     \item{final_scores}{Scores for all solutions in the final population}
#'     \item{parameters}{List of parameters used for the run}
#'     \item{statistics}{Additional information about cache hits etc.}
#'   }
#'
#' @details
#' The genetic algorithm uses the following operators:
#' \itemize{
#'   \item \strong{Selection}: Tournament selection with configurable size
#'   \item \strong{Crossover}: Single-point crossover on tree subtrees
#'   \item \strong{Mutation Type 1}: Add or remove a node (probability controlled by alpha)
#'   \item \strong{Mutation Type 2}: Swap a node with its parent or child
#'   \item \strong{Elitism}: Top solutions preserved unchanged
#' }
#'
#' The algorithm maintains a score cache to avoid redundant computations for
#' solutions that have been seen before (identified by hash).
#'
#' When \code{diversity = TRUE}, solutions are penalized based on their similarity
#' to other solutions in the population, encouraging exploration of diverse regions.
#'
#' @examples
#' \dontrun{
#' # Create example data
#' patient_df <- data.frame(
#'   patient_id = 1:100,
#'   outcome = rbinom(100, 1, 0.3)
#' )
#' patient_df$drugs <- lapply(1:100, function(i) sample(1:20, sample(1:5, 1)))
#'
#' # Define tree structure
#' tree_depth <- c(1, rep(2, 5), rep(3, 15))
#'
#' # Run GA
#' results <- run_genetic_algorithm(
#'   patient_data = patient_df,
#'   node_column = "drugs",
#'   target_column = "outcome",
#'   tree_depth = tree_depth,
#'   population_size = 50,
#'   epochs = 500,
#'   score_type = "hypergeometric",
#'   verbose = TRUE
#' )
#'
#' # View top results
#' print(results$top_scores)
#' print(results$top_solutions)
#' }
#'
#' @export
#' @seealso \code{\link{run_mcmc}} for an MCMC-based optimization approach
run_genetic_algorithm <- function(patient_data, node_column, target_column, tree_depth, seed_population = NULL, population_size = 100L, epochs = 1000L, mutation_rate = 0.1, prob_mutation_type1 = 0.2, crossover_rate = 0.8, elite_count = 0L, tournament_size = 3L, alpha = 1.0, score_type = "hypergeometric", diversity = FALSE, verbose = FALSE, seed = NULL) {
    .Call(`_treehunt_run_genetic_algorithm`, patient_data, node_column, target_column, tree_depth, seed_population, population_size, epochs, mutation_rate, prob_mutation_type1, crossover_rate, elite_count, tournament_size, alpha, score_type, diversity, verbose, seed)
}

#' Run MCMC Algorithm for Estimation of Score Distribution Among Nodes of The
#' Tree
#'
#' Performs a Modified Metropolis-Hastings MCMC sampling to estimate the score
#' distribution of nodes combination of a given \emph{cocktail_size}. The
#' algorithm explores the space of tree combinations using a proposal law 
#' composed of two mutation types.
#'
#' @param patient_data A data.frame containing patient information with at least
#'   a node column and a target column.
#' @param node_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the column containing drug codes. This column should be either:
#'   \itemize{
#'     \item A list of integer vectors: \code{list(c(1,2), c(3), c(4,5))}
#'     \item A character vector with comma-separated values: \code{c("1,2", "3", "4,5")}
#'   }
#' @param id_column Optional observation-unit identifier column, given by name
#'   or one-based column position; needed for patient-level scoring.
#' @param target_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the target/outcome column. Integer values are treated as binary for now,
#'   numeric values with non-0/1 entries are treated as continuous.
#' @param tree A data.frame containing the structural definition of the tree.
#' @param depth_column Either a string or integer specifying the column in 
#'   \code{tree} that contains the node depth levels.
#' @param upper_bound_column (Optional) Either a string or integer (1-based index) 
#'  specifying the column in \code{tree_depth} that contains upper 
#'  bound of nodes. Defaults to \code{NULL}.
#' @param name_column (Optional) Either a string or integer (1-based index) 
#'  specifying the column in \code{tree} that contains the corresponding name
#'  of nodes. Defaults to \code{NULL}.
#' @param epochs Number of MCMC iterations to run.
#' @param temperature Temperature parameter for the Metropolis-Hastings acceptance
#'   probability. Higher values lead to an easiest acceptance of lower score. Default: 1.0.
#' @param n_results Number of top solutions to track and return. Default: 10.
#' @param cocktail_size Target size of drug combinations to search for. Default: 2.
#' @param prob_type1 Probability of using Type 1 mutation (random generation) vs
#'   Type 2 mutation (local swap). Default: 0.01.
#' @param beta Strict support threshold: filtered results require more than
#'   beta covered observations (or distinct patients for patient-level scores). Default: 4.
#' @param max_score Finite positive cap applied to scores before Metropolis-Hastings
#'   acceptance, importance weighting and binning. Default: 200.0.
#' @param score_type Scoring function to use. Either "hypergeometric" for the
#'   hypergeometric test, "relative_risk" for relative risk calculation, or "wilcoxon"
#'   for the wilcoxon test with continuous output.
#'   Default: "hypergeometric".
#' @param verbose If TRUE, prints progress and statistics during the run.
#'   Default: FALSE.
#' @param seed Optional non-negative integer seed for the C++ random-number
#'   generator. If \code{NULL}, the generator is initialized non-deterministically.
#'
#' @param burn_in Number of initial iterations excluded from all distributions,
#'   top solutions and the optional trace. Must be smaller than epochs. Default: 0.
#' @param store_trace If TRUE, return the retained capped score, support and
#'   zero-based node vector for each iteration. Default FALSE avoids this storage.
#'
#' @return A list containing:
#'   \describe{
#'     \item{top_solutions}{List of zero-based node vectors for the top scoring solutions}
#'     \item{top_scores}{Numeric vector of scores for the top solutions}
#'     \item{top_solutions_filtered}{Top solutions meeting the beta threshold}
#'     \item{top_scores_filtered}{Scores for the filtered solutions}
#'     \item{score_distribution}{Histogram of retained capped scores (0.1-wide bins and a cap bin)}
#'     \item{score_distribution_filtered}{Histogram for solutions meeting beta threshold}
#'     \item{outstanding_scores}{Retained capped scores equal to max_score}
#'     \item{uniform_reference}{Uniform-reference distribution and weight ESS}
#'     \item{uniform_reference_filtered}{Support-filtered uniform reference and ESS}
#'     \item{reference_parameters}{Temperature, score cap, support and burn-in settings}
#'     \item{trace}{Retained trajectory, only when store_trace is TRUE}
#'     \item{statistics}{List of run statistics including acceptance rates}
#'   }
#'
#' @details
#' The stationary target on observed subsets of \code{cocktail_size} distinct
#' nodes is proportional to \eqn{\exp(S(C)/T)}, where \eqn{S} is capped at
#' \code{max_score}. Ancestor-descendant pairs are included in this MCMC space;
#' genetic-algorithm validity filtering is a separate operation.
#'
#' Type 1 proposes a uniform subset of distinct nodes. Type 2 replaces a node
#' by a parent or child not already in the combination. Its Hastings correction
#' is \eqn{|V(C)|/|V(C')|}, counting these possible local moves before rejecting
#' proposals absent from the data. Each acceptance probability is the minimum
#' of 1 and \eqn{\exp((S(C')-S(C))/T)} times the applicable proposal correction.
#' A positive \code{prob_type1} connects the observed state space.
#'
#' At every retained iteration, including rejected moves, weights proportional
#' to \eqn{\exp(-S(C)/T)} recover the uniform combination reference. Weights are
#' computed from exact capped scores before grouping into bins. They are
#' rescaled internally to avoid numerical underflow. The filtered reference
#' conditions on support strictly greater than \code{beta}, with its own ESS.
#' This estimates a uniform law on combinations, not on distinct score values.
#'
#' \code{uniform_reference} and \code{uniform_reference_filtered} each contain
#' \code{distribution}, \code{n_samples}, and \code{weight_ess}. The distribution
#' columns are \code{lower}, \code{upper}, \code{probability}, \code{cdf} and
#' \code{upper_tail}. Bins are [lower, upper), except the final singleton bin
#' at the cap. CDF includes the current bin; upper_tail includes it and all
#' subsequent bins. Empty references have NA probabilities and ESS.
#' ESS is \eqn{(\sum w)^2/\sum w^2}; it measures weight concentration and does
#' not account for MCMC autocorrelation. Check mixing separately and choose
#' an appropriate \code{burn_in}. See \code{\link{uniform_score_reference}}
#' for post-processing an optionally stored trace without binning.
#'
#' @examples
#' dat <- data.frame(outcome = c(1L, 1L, 0L, 0L))
#' dat$nodes <- list(c(0L, 1L), 0L, 1L, 1L)
#' tree <- data.frame(Depth = c(1L, 1L))
#' result <- run_mcmc_df_tree(dat, "nodes", "outcome", tree, "Depth",
#'   epochs = 100, cocktail_size = 1, seed = 42)
#' result$uniform_reference$weight_ess
#'
#' @export
run_mcmc_df_tree <- function(patient_data, node_column, target_column, tree, depth_column, upper_bound_column = NULL, name_column = NULL, id_column = NULL, epochs = 1e6, temperature = 1.0, n_results = 10, cocktail_size = 2, prob_type1 = 0.01, beta = 4, max_score = 200.0, score_type = "hypergeometric", verbose = FALSE, seed = NULL, burn_in = 0, store_trace = FALSE) {
    .Call(`_treehunt_run_mcmc_df_tree`, patient_data, node_column, target_column, tree, depth_column, upper_bound_column, name_column, id_column, epochs, temperature, n_results, cocktail_size, prob_type1, beta, max_score, score_type, verbose, seed, burn_in, store_trace)
}

#' Run Genetic Algorithm for High Score Nodes Combination Search
#'
#' Performs a genetic algorithm search to find optimal node combinations that
#' maximize a specified score function. This version builds the internal tree 
#' structure from a provided data frame mapping node depths and bounds.
#'
#' @param patient_data A data.frame containing patient information.
#' @param node_column Either a string (column name) or integer (1-based index)
#'   specifying the column containing node indexes (list of vectors or comma-separated strings).
#' @param id_column Optional observation-unit identifier column, given by name
#'   or one-based column position; needed for patient-level scoring.
#' @param target_column Either a string (column name) or integer (1-based index)
#'   specifying the target/outcome column.
#' @param tree A data.frame containing the structural definition of the tree.
#' @param depth_column Either a string or integer specifying the column in 
#'   \code{tree} that contains the node depth levels.
#' @param upper_bound_column (Optional) Either a string or integer (1-based index) 
#'  specifying the column in \code{tree_depth} that contains upper 
#'  bound of nodes. Defaults to \code{NULL}.
#' @param name_column (Optional) Either a string or integer (1-based index) 
#'  specifying the column in \code{tree} that contains the corresponding name
#'  of nodes. Defaults to \code{NULL}.
#' @param seed_population A \code{list} of integer vectors representing an initial 
#'   population (vector of 1-based tree index). If provided, these individuals 
#'   will be included in the first generation . If the list contains fewer 
#'   individuals than \code{population_size}, the remainder will be initialized 
#'   randomly. If \code{NULL} (the default), the entire initial population 
#'   is generated randomly.
#' @param population_size Number of solutions in the population. Default: 100.
#' @param epochs Number of generations to evolve. Default: 1000.
#' @param mutation_rate Probability of mutating each offspring. Default: 0.1.
#' @param prob_mutation_type1 Probability of using Type 1 (add/remove) vs Type 2 (swap) mutation. Default: 0.2.
#' @param crossover_rate Probability of applying crossover to selected parents. Default: 0.8.
#' @param elite_count Number of top solutions to preserve unchanged each generation. Default: 0.
#' @param tournament_size Number of solutions competing in tournament selection. Default: 3.
#' @param alpha Parameter controlling add/remove mutation bias. Higher values favor adding nodes. Default: 1.0.
#' @param score_type Scoring function: "hypergeometric", "relative_risk", or "wilcoxon".
#' @param diversity If TRUE, applies a diversity penalty to encourage exploration. Default: FALSE.
#' @param verbose If TRUE, prints progress during the run. Default: FALSE.
#' @param seed Optional non-negative integer seed for the C++ random-number
#'   generator. If \code{NULL}, the generator is initialized non-deterministically.
#'
#' @return A list containing:
#'   \describe{
#'     \item{final_population}{The complete final population of solutions, 0-based
#'     tree index. TODO -> return 1 based (R-like) index for more coherence}
#'     \item{final_scores}{Scores for all solutions in the final population}
#'     \item{parameters}{List of parameters used for the run}
#'     \item{statistics}{Additional information about cache hits, etc.}
#'   }
#'
#' @details
#' Unlike the vector-based version, this function extracts tree hierarchy from 
#' the \code{tree_depth} data frame. It uses \code{depth_column} and optionally 
#' \code{upper_bound_column} and \code{name_column} to define the tree.
#'
#' @examples
#' \dontrun{
#' # Define tree structure via data frame
#' tree_df <- data.frame(
#'   node_id = 1:21,
#'   depth_level = c(1, rep(2, 5), rep(3, 15)), # User may add, upper bound 
#'   # and name column
#' )
#'
#' results <- run_genetic_algorithm_df_tree(
#'   patient_data = patient_df,
#'   node_column = "drugs",
#'   target_column = "outcome",
#'   tree = tree_df,
#'   depth_column = "depth_level", # or 2
#'   population_size = 100,
#'   score_type = "hypergeometric"
#' )
#' }
#'
#' @export
run_genetic_algorithm_df_tree <- function(patient_data, node_column, target_column, tree, depth_column, upper_bound_column = NULL, name_column = NULL, id_column = NULL, seed_population = NULL, population_size = 100L, epochs = 1000L, mutation_rate = 0.1, prob_mutation_type1 = 0.2, crossover_rate = 0.8, elite_count = 0L, tournament_size = 3L, alpha = 1.0, score_type = "hypergeometric", diversity = FALSE, verbose = FALSE, seed = NULL) {
    .Call(`_treehunt_run_genetic_algorithm_df_tree`, patient_data, node_column, target_column, tree, depth_column, upper_bound_column, name_column, id_column, seed_population, population_size, epochs, mutation_rate, prob_mutation_type1, crossover_rate, elite_count, tournament_size, alpha, score_type, diversity, verbose, seed)
}

#' Run MCMC Algorithm to Compute the Score Distribution Among Node Combinations 
#' of Size 2
#'
#' Performs a Modified Metropolis-Hastings MCMC sampling to compute the score
#' distribution of nodes combination of size \emph{cocktail_size}.
#'
#' @param patient_data A data.frame containing patient information with at least
#'   a node column and a target column.
#' @param node_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the column containing drug codes. This column should be either:
#'   \itemize{
#'     \item A list of integer vectors: \code{list(c(1,2), c(3), c(4,5))}
#'     \item A character vector with comma-separated values: \code{c("1,2", "3", "4,5")}
#'   }
#' @param id_column Optional observation-unit identifier column, given by name
#'   or one-based column position; needed for patient-level scoring.
#' @param target_column Either a string (column name) or integer (column index, 1-based)
#'   specifying the target/outcome column. Integer values are treated as binary for now,
#'   numeric values with non-0/1 entries are treated as continuous.
#' @param tree A data.frame containing the structural definition of the tree.
#' @param depth_column Either a string or integer specifying the column in 
#'   \code{tree} that contains the node depth levels.
#' @param upper_bound_column (Optional) Either a string or integer (1-based index) 
#'  specifying the column in \code{tree_depth} that contains upper 
#'  bound of nodes. Defaults to \code{NULL}.
#' @param name_column (Optional) Either a string or integer (1-based index) 
#'  specifying the column in \code{tree} that contains the corresponding name
#'  of nodes. Defaults to \code{NULL}.
#' @param beta Strict support threshold: filtered results require more than
#'   beta covered observations (or distinct patients for patient-level scores). Default: 4.
#' @param max_score Finite positive cap applied to scores before Metropolis-Hastings
#'   acceptance, importance weighting and binning. Default: 200.0.
#' @param score_type Scoring function to use. Either "hypergeometric" for the
#'   hypergeometric test, "relative_risk" for relative risk calculation, or "wilcoxon"
#'   for the wilcoxon test with continuous output.
#'   Default: "hypergeometric".
#'
#' @return A list containing:
#'   \describe{
#'     \item{top_solutions}{List of zero-based node vectors for the top scoring solutions}
#'     \item{top_scores}{Numeric vector of scores for the top solutions}
#'     \item{top_solutions_filtered}{Top solutions meeting the beta threshold}
#'     \item{top_scores_filtered}{Scores for the filtered solutions}
#'     \item{score_distribution}{Histogram of retained capped scores (0.1-wide bins and a cap bin)}
#'     \item{score_distribution_filtered}{Histogram for solutions meeting beta threshold}
#'     \item{outstanding_scores}{Retained capped scores equal to max_score}
#'     \item{uniform_reference}{Uniform-reference distribution and weight ESS}
#'     \item{uniform_reference_filtered}{Support-filtered uniform reference and ESS}
#'     \item{reference_parameters}{Temperature, score cap, support and burn-in settings}
#'     \item{trace}{Retained trajectory, only when store_trace is TRUE}
#'     \item{statistics}{List of run statistics including acceptance rates}
#'   }
#'
#' @details
#' Enumerates each unordered pair of distinct nodes exactly once and retains
#' pairs present in at least one observation, including ancestor-descendant
#' pairs. It uses the same state space, cap and strict support filter as
#' \code{run_mcmc_df_tree(cocktail_size = 2)}. No MCMC or importance weighting
#' is performed: each enumerated pair has unit weight. The returned
#' \code{uniform_reference} is exact; its \code{weight_ess} equals the number
#' of enumerated pairs. Acceptance statistics are not applicable.
#'
#' @examples
#' dat <- data.frame(outcome = c(1L, 1L, 0L, 0L))
#' dat$nodes <- list(c(0L, 1L), 0L, 1L, 1L)
#' tree <- data.frame(Depth = c(1L, 1L))
#' result <- mcmc_size_2_true_score_distribution(dat, "nodes", "outcome", tree, "Depth")
#' result$uniform_reference$weight_ess
#'
#' @export
mcmc_size_2_true_score_distribution <- function(patient_data, node_column, target_column, tree, depth_column, upper_bound_column = NULL, name_column = NULL, id_column = NULL, beta = 4, max_score = 200.0, score_type = "hypergeometric") {
    .Call(`_treehunt_mcmc_size_2_true_score_distribution`, patient_data, node_column, target_column, tree, depth_column, upper_bound_column, name_column, id_column, beta, max_score, score_type)
}

#' Compute scores for supplied node combinations
#'
#' @param cocktail_list List of integer vectors identifying tree rows with
#'   one-based R indices. The returned \code{solutions} retain these indices.
#' @param patient_data Observation data frame. Its node list-column uses the
#'   package's zero-based internal tree indices.
#' @param node_column Name or one-based position of the node list-column.
#' @param target_column Name or one-based position of the outcome column.
#' @param tree Tree data frame in depth-first order.
#' @param depth_column Name or one-based position of the tree-depth column.
#' @param id_column Optional name or one-based position of the observation-unit
#'   identifier. It is required by patient-level continuous-outcome scores.
#' @param upper_bound_column Optional name or one-based position of the
#'   zero-based inclusive subtree upper-bound column.
#' @param name_column Optional name or one-based position of the node-label column.
#' @param score_type Registered score implementation to evaluate.
#' @return A list containing the supplied combinations, their scores, coverage
#'   counts, and score-specific summaries.
#' @details Candidate vectors deliberately use ordinary one-based R row
#'   positions at this user-facing boundary. They are checked against the tree
#'   before being converted once to the zero-based representation used by the
#'   C++ scoring engine.
#' @export
compute_score <- function(cocktail_list, patient_data, node_column, target_column, tree, depth_column, id_column = NULL, upper_bound_column = NULL, name_column = NULL, score_type = "hypergeometric") {
    .Call(`_treehunt_compute_score`, cocktail_list, patient_data, node_column, target_column, tree, depth_column, id_column, upper_bound_column, name_column, score_type)
}

#' Compute the dissimilarity matrix on a list of cocktails
#'
#' @inheritParams compute_score
#' @return A symmetric numeric matrix of normalized greedy tree-edit dissimilarities.
#' @export
get_dissimilarity_of_list <- function(cocktail_list, patient_data, node_column, target_column, tree, depth_column, upper_bound_column = NULL, name_column = NULL, score_type = "wilcoxon") {
    .Call(`_treehunt_get_dissimilarity_of_list`, cocktail_list, patient_data, node_column, target_column, tree, depth_column, upper_bound_column, name_column, score_type)
}

#' Identify observations covered by hierarchical combinations
#'
#' @inheritParams compute_score
#' @param cocktail_list List of zero-based node-index vectors.
#' @param id_column Name of the integer patient identifier column.
#' @param hadm_column Name of the integer admission identifier column.
#' @return A list with the supplied combinations (`cocktail_list`), distinct
#'   patient identifiers (`Takers_set`), admission identifiers (`hadm_set`),
#'   and one-based observation rows (`idx_set`) for each combination.
#' @export
get_taker <- function(cocktail_list, patient_data, node_column, target_column, id_column, hadm_column, tree, depth_column, upper_bound_column = NULL, name_column = NULL) {
    .Call(`_treehunt_get_taker`, cocktail_list, patient_data, node_column, target_column, id_column, hadm_column, tree, depth_column, upper_bound_column, name_column)
}

